### PR TITLE
Allowed to specify ref argument to git/github projects.

### PR DESCRIPTION
**Pull request by benwiley4000**
This is a review for a change that will be submitted upstream.

Licensee is a ruby gem and command line tool for searching a software library for its license text and checking that text for conformity with a known license type. This gives us a more reliable automated license report than reading from the package.json.

I haven't yet provided tests. Might need help there. I'm new to Ruby.

### CODE REVIEW

**Review by antoinehebert — APPROVED** [review]
lgtm

**Review by zaratan — APPROVED** [review]
Seeing a `while` is weird in ruby world. But… it's seems right.

Sorry for not reviewing earlier, was shipping 8.0.2

**Comment by benwiley4000** [comment]
@denispasin is there a way that would look more natural to you?

**Comment by zaratan** [comment]
If you don't know the depth, it will probably be the best way.

**Comment by benwiley4000** [comment]
If I knew more about git I would probably know the depth, but I think this would require a lot of research..

**Pull request closed without merging**
